
- hosts: "{{ HOST_NAME }}" 
  become: yes
  gather_facts: false
  tasks:
    - name: "Restart Agent"
      become: yes
      shell: |
          rm -f /test1  # This should be an error.
          echo "test2"
          echo "test1"
          echo "test3" # success
